import type {
  AiRoute,
  ClinicalContextBundle,
  ClinicalSourceNote,
  DraftNote,
  DraftNoteBody,
  SourceMapEntry,
} from "./types";
import {
  buildAuditEntry,
  loadUcsfAiPolicyFromEnv,
  preflightCheck,
  type UcsfAiPolicyConfig,
} from "./ucsfAiPolicy";

const NOT_FOUND = "[Not found in provided notes]";

export interface DrafterOptions {
  draftNoteType?: string;
  anthropicClient?: AnthropicLike | null;
  anthropicModel?: string;
  ucsfAiPolicy?: UcsfAiPolicyConfig;
  versaClient?: AnthropicLike | null;
}

export interface AnthropicLike {
  messages: {
    create(args: {
      model: string;
      max_tokens: number;
      system: string;
      messages: Array<{ role: "user"; content: string }>;
    }): Promise<{ content: Array<{ type: string; text?: string }> }>;
  };
}

const SYSTEM_PROMPT = `You are a clinical documentation assistant.
You ONLY produce notes whose content is drawn from the source notes the user provides.
Never invent diagnoses, medications, doses, allergies, lab values, imaging results, procedures, orders, or demographics.
If the information is not in the source notes, write exactly: ${NOT_FOUND}
Every clinical statement in the draft must be traceable to one or more source_ids.
Return ONLY valid JSON matching the requested schema.`;

const REQUIRED_SHAPE = {
  draft_note_type: "string",
  summary: "string",
  draft_note: {
    chief_complaint: "string",
    hpi: "string",
    past_medical_history: "string",
    medications: "string",
    allergies: "string",
    physical_exam: "string",
    labs_imaging: "string",
    assessment_and_plan: "string",
  },
  uncertain_or_missing_info: ["string"],
  source_map: [{ claim: "string", source_ids: ["string"] }],
  warnings: ["string"],
};

function pickFirstSection(
  sources: ClinicalSourceNote[],
  key: keyof NonNullable<ClinicalSourceNote["extractedSections"]>,
): { text: string; sourceIds: string[] } {
  const matched = sources.filter((s) => s.extractedSections?.[key]);
  if (matched.length === 0) return { text: "", sourceIds: [] };
  const combined = matched
    .map((s) => `(${s.id}) ${s.extractedSections![key]}`)
    .join("\n");
  return { text: combined, sourceIds: matched.map((s) => s.id) };
}

function buildFallbackDraft(
  bundle: ClinicalContextBundle,
  draftNoteType: string,
): DraftNote {
  const sources = bundle.sources;
  const sourceMap: SourceMapEntry[] = [];
  const missing: string[] = [];

  const draft: DraftNoteBody = {
    chief_complaint: NOT_FOUND,
    hpi: NOT_FOUND,
    past_medical_history: NOT_FOUND,
    medications: NOT_FOUND,
    allergies: NOT_FOUND,
    physical_exam: NOT_FOUND,
    labs_imaging: NOT_FOUND,
    assessment_and_plan: NOT_FOUND,
  };

  const fields: Array<
    [
      keyof DraftNoteBody,
      keyof NonNullable<ClinicalSourceNote["extractedSections"]>,
      string,
    ]
  > = [
    ["chief_complaint", "chiefComplaint", "Chief complaint"],
    ["hpi", "hpi", "HPI"],
    ["past_medical_history", "pmh", "PMH"],
    ["medications", "meds", "Medications"],
    ["allergies", "allergies", "Allergies"],
    ["physical_exam", "exam", "Physical exam"],
    ["labs_imaging", "labs", "Labs/Imaging"],
    ["assessment_and_plan", "assessmentPlan", "Assessment and plan"],
  ];

  for (const [draftField, sectionKey, label] of fields) {
    const picked = pickFirstSection(sources, sectionKey);
    if (picked.text) {
      draft[draftField] = picked.text;
      sourceMap.push({
        claim: `${label} content quoted verbatim from source notes`,
        source_ids: picked.sourceIds,
      });
    } else {
      missing.push(label);
    }
  }

  // Imaging fallback: if labs section had imaging text in any source, attribute it
  if (draft.labs_imaging === NOT_FOUND) {
    const imaging = pickFirstSection(sources, "imaging");
    if (imaging.text) {
      draft.labs_imaging = imaging.text;
      sourceMap.push({
        claim: "Imaging content quoted verbatim from source notes",
        source_ids: imaging.sourceIds,
      });
      const idx = missing.indexOf("Labs/Imaging");
      if (idx >= 0) missing.splice(idx, 1);
    }
  }

  const summaryParts: string[] = [];
  for (const s of sources) {
    summaryParts.push(`${s.id} (${s.noteType ?? "note"})`);
  }

  return {
    draft_note_type: draftNoteType,
    summary: `Synthesized from ${sources.length} source note(s): ${summaryParts.join(", ")}.`,
    draft_note: draft,
    uncertain_or_missing_info: missing,
    source_map: sourceMap,
    warnings: [
      "Clinician must verify all content before signing.",
      "Generated by source-grounded fallback (no LLM call).",
    ],
    generator: "fixture_grounded_fallback",
  };
}

function extractJsonBlock(text: string): unknown {
  const fenced = text.match(/```(?:json)?\s*([\s\S]*?)```/i);
  const candidate = fenced?.[1] || text.match(/\{[\s\S]*\}/)?.[0] || text;
  return JSON.parse(candidate);
}

function coerceStringArray(value: unknown): string[] {
  return Array.isArray(value)
    ? value.filter((v): v is string => typeof v === "string")
    : [];
}

function coerceSourceMap(value: unknown): SourceMapEntry[] {
  if (!Array.isArray(value)) return [];
  return value
    .filter((v): v is Record<string, unknown> =>
      Boolean(v && typeof v === "object"),
    )
    .map((entry) => ({
      claim: typeof entry.claim === "string" ? entry.claim : "",
      source_ids: coerceStringArray(entry.source_ids),
    }))
    .filter((e) => e.claim && e.source_ids.length > 0);
}

function coerceDraftBody(value: unknown): DraftNoteBody {
  const v = (value && typeof value === "object" ? value : {}) as Record<
    string,
    unknown
  >;
  const get = (k: string): string =>
    typeof v[k] === "string" && (v[k] as string).trim().length > 0
      ? (v[k] as string)
      : NOT_FOUND;
  return {
    chief_complaint: get("chief_complaint"),
    hpi: get("hpi"),
    past_medical_history: get("past_medical_history"),
    medications: get("medications"),
    allergies: get("allergies"),
    physical_exam: get("physical_exam"),
    labs_imaging: get("labs_imaging"),
    assessment_and_plan: get("assessment_and_plan"),
  };
}

function normalizeAnthropicDraft(
  raw: unknown,
  draftNoteType: string,
): DraftNote {
  const obj = (raw && typeof raw === "object" ? raw : {}) as Record<
    string,
    unknown
  >;
  return {
    draft_note_type:
      typeof obj.draft_note_type === "string" && obj.draft_note_type.trim()
        ? obj.draft_note_type
        : draftNoteType,
    summary: typeof obj.summary === "string" ? obj.summary : "",
    draft_note: coerceDraftBody(obj.draft_note),
    uncertain_or_missing_info: coerceStringArray(obj.uncertain_or_missing_info),
    source_map: coerceSourceMap(obj.source_map),
    warnings: [
      ...coerceStringArray(obj.warnings),
      "Clinician must verify all content before signing.",
    ],
    generator: "anthropic",
  };
}

export async function generateDraftNote(
  bundle: ClinicalContextBundle,
  options: DrafterOptions = {},
): Promise<DraftNote> {
  const draftNoteType = options.draftNoteType || "Progress Note";

  if (bundle.sources.length === 0) {
    return {
      draft_note_type: draftNoteType,
      summary: "No source notes captured.",
      draft_note: {
        chief_complaint: NOT_FOUND,
        hpi: NOT_FOUND,
        past_medical_history: NOT_FOUND,
        medications: NOT_FOUND,
        allergies: NOT_FOUND,
        physical_exam: NOT_FOUND,
        labs_imaging: NOT_FOUND,
        assessment_and_plan: NOT_FOUND,
      },
      uncertain_or_missing_info: ["all sections — no sources provided"],
      source_map: [],
      warnings: [
        "No source notes were captured. Refusing to draft from empty context.",
      ],
      generator: "fixture_grounded_fallback",
    };
  }

  const policy = options.ucsfAiPolicy ?? loadUcsfAiPolicyFromEnv();
  const preflight = preflightCheck({ bundle, config: policy });
  const audit = buildAuditEntry(bundle, preflight);

  if (!preflight.permitted) {
    const fallback = buildFallbackDraft(bundle, draftNoteType);
    fallback.ai_route = "blocked";
    fallback.warnings = [
      ...fallback.warnings,
      `LLM call blocked by UCSF AI policy: ${preflight.reason}`,
      ...preflight.warnings,
      `audit: ${JSON.stringify(audit)}`,
    ];
    return fallback;
  }

  const client: AnthropicLike | null =
    preflight.effectiveRoute === "ucsf_versa"
      ? (options.versaClient ?? null)
      : preflight.effectiveRoute === "anthropic_direct"
        ? (options.anthropicClient ?? null)
        : null;

  if (!client) {
    const fallback = buildFallbackDraft(bundle, draftNoteType);
    fallback.ai_route = "mock";
    fallback.warnings = [
      ...fallback.warnings,
      ...preflight.warnings,
      `audit: ${JSON.stringify(audit)}`,
    ];
    return fallback;
  }

  try {
    const userPayload = {
      draft_note_type: draftNoteType,
      sources: bundle.sources.map((s) => ({
        source_id: s.id,
        note_type: s.noteType,
        author: s.author,
        timestamp: s.timestamp,
        raw_text: s.rawText,
      })),
      required_shape: REQUIRED_SHAPE,
      rules: [
        "Use ONLY content present in sources.",
        "If a section is missing, output exactly: " + NOT_FOUND,
        "Every clinical statement must map to >=1 source_id in source_map.",
        "Do not invent diagnoses, meds, allergies, labs, imaging, procedures, orders, or demographics.",
      ],
    };
    const response = await client.messages.create({
      model: options.anthropicModel || "claude-opus-4-7",
      max_tokens: 4096,
      system: SYSTEM_PROMPT,
      messages: [
        { role: "user", content: JSON.stringify(userPayload, null, 2) },
      ],
    });
    const text = response.content
      .map((p) =>
        p.type === "text" && typeof p.text === "string" ? p.text : "",
      )
      .join("\n");
    const parsed = extractJsonBlock(text);
    const normalized = normalizeAnthropicDraft(parsed, draftNoteType);
    normalized.ai_route = preflight.effectiveRoute as AiRoute;
    normalized.generator =
      preflight.effectiveRoute === "ucsf_versa" ? "ucsf_versa" : "anthropic";
    normalized.warnings = [
      ...normalized.warnings,
      ...preflight.warnings,
      `audit: ${JSON.stringify(audit)}`,
    ];
    return normalized;
  } catch {
    const fallback = buildFallbackDraft(bundle, draftNoteType);
    fallback.ai_route = preflight.effectiveRoute as AiRoute;
    fallback.warnings = [
      ...fallback.warnings,
      `audit: ${JSON.stringify(audit)}`,
    ];
    return fallback;
  }
}

export interface ValidationResult {
  ok: boolean;
  errors: string[];
}

export function validateDraft(
  draft: DraftNote,
  bundle: ClinicalContextBundle,
): ValidationResult {
  const errors: string[] = [];
  const validIds = new Set(bundle.sources.map((s) => s.id));

  for (const entry of draft.source_map) {
    for (const id of entry.source_ids) {
      if (!validIds.has(id)) {
        errors.push(`source_map references unknown source_id ${id}`);
      }
    }
  }

  const populatedSections = Object.entries(draft.draft_note).filter(
    ([, v]) => v && v !== NOT_FOUND,
  );
  if (populatedSections.length > 0 && draft.source_map.length === 0) {
    errors.push("draft has populated sections but empty source_map");
  }

  if (
    !draft.warnings.some((w) => /clinician.*verify|verify.*signing/i.test(w))
  ) {
    errors.push("missing clinician-verification warning");
  }

  return { ok: errors.length === 0, errors };
}
