import type {
  EhrAction,
  EhrWorkflowState,
  UiTarget,
  WorkflowTransition,
} from "./types";

export const EHR_TARGETS: Record<string, UiTarget> = {
  patientChart: {
    label: "Patient chart",
    type: "panel",
    expectedRegion: "main_workspace",
    safetyLevel: "read_only",
  },
  summaryTab: {
    label: "Summary",
    type: "tab",
    textAnchors: ["Summary"],
    expectedRegion: "top_navigation",
    safetyLevel: "read_only",
  },
  chartReviewTab: {
    label: "Chart Review",
    type: "tab",
    textAnchors: ["Chart Review"],
    expectedRegion: "top_navigation",
    safetyLevel: "read_only",
  },
  notesSubtab: {
    label: "Notes",
    type: "tab",
    textAnchors: ["Notes"],
    expectedRegion: "chart_review_subtab_strip",
    safetyLevel: "read_only",
  },
  filterByType: {
    label: "Filter by Type",
    type: "menu",
    textAnchors: ["Filters", "Default Filter", "Type"],
    expectedRegion: "chart_review_left_panel",
    safetyLevel: "read_only",
  },
  inpatientTypeOption: {
    label: "Inpatient note type",
    type: "menu",
    textAnchors: ["Inpatient", "H&P", "Admission"],
    expectedRegion: "filter_dropdown",
    safetyLevel: "read_only",
  },
  inpatientNoteRow: {
    label: "Inpatient/H&P note row",
    type: "row",
    textAnchors: ["H&P", "History and Physical", "Inpatient"],
    expectedRegion: "chart_review_notes_list",
    safetyLevel: "read_only",
  },
  notePreviewPane: {
    label: "Note preview pane",
    type: "panel",
    expectedRegion: "chart_review_right_panel",
    safetyLevel: "read_only",
  },
  notesActivityTab: {
    label: "Notes (top activity)",
    type: "tab",
    textAnchors: ["Notes"],
    expectedRegion: "top_navigation",
    safetyLevel: "read_only",
  },
  notesList: {
    label: "Notes list",
    type: "list",
    expectedRegion: "notes_activity_left",
    safetyLevel: "read_only",
  },
  newNoteButton: {
    label: "New Note",
    type: "button",
    textAnchors: ["New Note"],
    expectedRegion: "notes_toolbar",
    safetyLevel: "draft_only",
  },
  myNoteEditor: {
    label: "My Note rich text editor",
    type: "field",
    expectedRegion: "notes_main_pane",
    safetyLevel: "draft_only",
  },
  signNoteButton: {
    label: "Sign note",
    type: "button",
    textAnchors: ["Sign"],
    expectedRegion: "notes_main_pane_footer",
    safetyLevel: "prohibited",
  },
  ordersTab: {
    label: "Orders",
    type: "tab",
    textAnchors: ["Orders"],
    expectedRegion: "top_navigation",
    safetyLevel: "read_only",
  },
  orderSearchField: {
    label: "Order search field",
    type: "input",
    textAnchors: ["Search", "New Order"],
    expectedRegion: "orders_right_sidebar",
    safetyLevel: "draft_only",
  },
  orderHydromorphone: {
    label: "HYDROmorphone (Dilaudid) injection",
    type: "row",
    textAnchors: ["HYDROmorphone", "Dilaudid"],
    expectedRegion: "order_search_results",
    safetyLevel: "clinician_confirmed",
  },
  alternativeAdvisory: {
    label: "Alternative Selection advisory",
    type: "advisory",
    textAnchors: ["Alternative Selection", "Shortage", "Formulary"],
    expectedRegion: "modal",
    safetyLevel: "clinician_confirmed",
  },
  reasonDropdown: {
    label: "Reason dropdown",
    type: "menu",
    textAnchors: ["Reason"],
    expectedRegion: "advisory_modal",
    safetyLevel: "clinician_confirmed",
  },
  orderComposer: {
    label: "Order composer",
    type: "dialog",
    expectedRegion: "modal",
    safetyLevel: "draft_only",
  },
  acceptOrderButton: {
    label: "Accept order",
    type: "button",
    textAnchors: ["Accept"],
    expectedRegion: "order_composer_footer",
    safetyLevel: "clinician_confirmed",
  },
  signOrdersButton: {
    label: "Sign Orders",
    type: "button",
    textAnchors: ["Sign Orders"],
    expectedRegion: "orders_footer",
    safetyLevel: "prohibited",
  },
};

function action(a: EhrAction): EhrAction {
  return a;
}

export function compileEhrWorkflow(): EhrAction[] {
  return [
    action({
      id: "p1.confirm_patient_context",
      phase: "patient_context",
      action: "observe",
      semanticTarget: EHR_TARGETS.patientChart,
      reason: "Confirm active patient encounter before chart review",
      preconditions: ["patient_chart_visible"],
      postconditions: ["patient_context_open"],
      safetyLevel: "read_only",
      replayAllowed: true,
    }),
    action({
      id: "p2.click_chart_review",
      phase: "chart_review",
      action: "click",
      semanticTarget: EHR_TARGETS.chartReviewTab,
      reason: "Enter historical chart documentation area",
      postconditions: ["chart_review_open"],
      safetyLevel: "read_only",
      replayAllowed: true,
    }),
    action({
      id: "p2.click_notes_subtab",
      phase: "chart_review",
      action: "click",
      semanticTarget: EHR_TARGETS.notesSubtab,
      reason: "Open prior notes subview",
      preconditions: ["chart_review_open"],
      postconditions: ["chart_review_notes_visible"],
      safetyLevel: "read_only",
      replayAllowed: true,
    }),
    action({
      id: "p2.open_filter",
      phase: "chart_review",
      action: "open_filter",
      semanticTarget: EHR_TARGETS.filterByType,
      reason: "Restrict note list to relevant clinical note types",
      preconditions: ["chart_review_notes_visible"],
      postconditions: ["filter_panel_open"],
      safetyLevel: "read_only",
      replayAllowed: true,
    }),
    action({
      id: "p2.select_inpatient_type",
      phase: "chart_review",
      action: "select_filter_value",
      semanticTarget: EHR_TARGETS.inpatientTypeOption,
      reason: "Focus on inpatient/H&P documentation",
      preconditions: ["filter_panel_open"],
      postconditions: ["notes_filtered_inpatient"],
      safetyLevel: "read_only",
      replayAllowed: true,
    }),
    action({
      id: "p2.open_inpatient_note",
      phase: "chart_review",
      action: "open_note",
      semanticTarget: EHR_TARGETS.inpatientNoteRow,
      reason: "Review source note for history, exam, assessment, plan",
      preconditions: ["notes_filtered_inpatient"],
      postconditions: ["note_preview_open"],
      safetyLevel: "read_only",
      replayAllowed: true,
    }),
    action({
      id: "p3.select_note_text",
      phase: "capture_inpatient_note",
      action: "select_text",
      semanticTarget: EHR_TARGETS.notePreviewPane,
      reason: "Select all text in inpatient/H&P note for capture",
      preconditions: ["note_preview_open"],
      postconditions: ["text_selected"],
      safetyLevel: "read_only",
      replayAllowed: true,
      payload: { keys: ["Cmd", "A"] },
    }),
    action({
      id: "p3.copy_note_text",
      phase: "capture_inpatient_note",
      action: "copy",
      semanticTarget: EHR_TARGETS.notePreviewPane,
      reason: "Copy selected text into clipboard for context bundle",
      preconditions: ["text_selected"],
      postconditions: ["clipboard_has_inpatient_note"],
      safetyLevel: "read_only",
      replayAllowed: true,
      payload: { keys: ["Cmd", "C"] },
    }),
    action({
      id: "p4.click_notes_activity",
      phase: "collect_additional_notes",
      action: "click",
      semanticTarget: EHR_TARGETS.notesActivityTab,
      reason: "Open main note activity with more notes",
      postconditions: ["notes_activity_open"],
      safetyLevel: "read_only",
      replayAllowed: true,
    }),
    action({
      id: "p4.iterate_note_rows",
      phase: "collect_additional_notes",
      action: "iterate_note_rows",
      semanticTarget: EHR_TARGETS.notesList,
      reason: "Review each relevant clinical source",
      preconditions: ["notes_activity_open"],
      postconditions: ["multi_note_review_in_progress"],
      safetyLevel: "read_only",
      replayAllowed: true,
    }),
    action({
      id: "p4.open_each_note_preview",
      phase: "collect_additional_notes",
      action: "open_note_preview",
      semanticTarget: EHR_TARGETS.notePreviewPane,
      reason: "Expose note content per row",
      preconditions: ["multi_note_review_in_progress"],
      postconditions: ["additional_note_preview_open"],
      safetyLevel: "read_only",
      replayAllowed: true,
    }),
    action({
      id: "p4.copy_each_note",
      phase: "collect_additional_notes",
      action: "copy",
      semanticTarget: EHR_TARGETS.notePreviewPane,
      reason: "Add source text to LLM context bundle",
      preconditions: ["additional_note_preview_open"],
      postconditions: ["context_bundle_has_source"],
      safetyLevel: "read_only",
      replayAllowed: true,
      payload: { keys: ["Cmd", "C"] },
    }),
    action({
      id: "p5.click_new_note",
      phase: "draft_new_note",
      action: "click",
      semanticTarget: EHR_TARGETS.newNoteButton,
      reason: "Create a new clinical note",
      preconditions: ["notes_activity_open"],
      postconditions: ["new_note_editor_open"],
      safetyLevel: "draft_only",
      replayAllowed: true,
    }),
    action({
      id: "p5.wait_for_editor",
      phase: "draft_new_note",
      action: "wait_for_ui",
      semanticTarget: EHR_TARGETS.myNoteEditor,
      reason: "Ensure note editor is ready",
      postconditions: ["editor_ready"],
      safetyLevel: "read_only",
      replayAllowed: true,
    }),
    action({
      id: "p5.paste_draft",
      phase: "draft_new_note",
      action: "paste",
      semanticTarget: EHR_TARGETS.myNoteEditor,
      reason: "Insert source-grounded synthesized draft",
      preconditions: ["editor_ready", "draft_validated"],
      postconditions: ["draft_inserted"],
      safetyLevel: "draft_only",
      replayAllowed: true,
      payload: { keys: ["Cmd", "V"] },
    }),
    action({
      id: "p5.clinician_review_required",
      phase: "draft_new_note",
      action: "confirm_modal",
      semanticTarget: EHR_TARGETS.myNoteEditor,
      reason: "Clinician must verify all content before signing",
      preconditions: ["draft_inserted"],
      postconditions: ["clinician_reviewed_draft"],
      safetyLevel: "clinician_confirmed",
      replayAllowed: false,
    }),
    action({
      id: "p5.manual_sign_note",
      phase: "draft_new_note",
      action: "manual_sign_only",
      semanticTarget: EHR_TARGETS.signNoteButton,
      reason: "Signing must remain clinician-controlled",
      preconditions: ["clinician_reviewed_draft"],
      postconditions: ["note_signed_by_clinician"],
      safetyLevel: "prohibited",
      replayAllowed: false,
    }),
    action({
      id: "p6.click_orders_tab",
      phase: "order_entry",
      action: "click",
      semanticTarget: EHR_TARGETS.ordersTab,
      reason: "Enter order management workflow",
      postconditions: ["orders_open"],
      safetyLevel: "read_only",
      replayAllowed: true,
    }),
    action({
      id: "p6.click_order_search",
      phase: "order_entry",
      action: "click",
      semanticTarget: EHR_TARGETS.orderSearchField,
      reason: "Search for medication order",
      preconditions: ["orders_open"],
      postconditions: ["order_search_active"],
      safetyLevel: "read_only",
      replayAllowed: true,
    }),
    action({
      id: "p6.type_dilaudid",
      phase: "order_entry",
      action: "type",
      semanticTarget: EHR_TARGETS.orderSearchField,
      reason: "Find hydromorphone order options",
      preconditions: ["order_search_active"],
      postconditions: ["order_search_results_visible"],
      safetyLevel: "read_only",
      replayAllowed: true,
      payload: { text: "DILAUDID" },
    }),
    action({
      id: "p6.select_hydromorphone",
      phase: "order_entry",
      action: "select_order_option",
      semanticTarget: EHR_TARGETS.orderHydromorphone,
      reason: "Choose intended pain medication order",
      preconditions: ["order_search_results_visible"],
      postconditions: ["medication_selected"],
      safetyLevel: "clinician_confirmed",
      replayAllowed: false,
    }),
    action({
      id: "p6.handle_advisory",
      phase: "order_entry",
      action: "handle_advisory",
      semanticTarget: EHR_TARGETS.alternativeAdvisory,
      reason:
        "Acknowledge shortage/alternative guidance — never bypass autonomously",
      preconditions: ["medication_selected"],
      postconditions: ["advisory_acknowledged"],
      safetyLevel: "clinician_confirmed",
      replayAllowed: false,
    }),
    action({
      id: "p6.select_reason",
      phase: "order_entry",
      action: "select_reason",
      semanticTarget: EHR_TARGETS.reasonDropdown,
      reason: "Required to continue past advisory",
      preconditions: ["advisory_acknowledged"],
      postconditions: ["reason_selected"],
      safetyLevel: "clinician_confirmed",
      replayAllowed: false,
    }),
    action({
      id: "p6.configure_order",
      phase: "order_entry",
      action: "configure_order",
      semanticTarget: EHR_TARGETS.orderComposer,
      reason: "Complete medication order details",
      preconditions: ["reason_selected"],
      postconditions: ["order_configured"],
      safetyLevel: "draft_only",
      replayAllowed: true,
      payload: {
        fields: {
          dose: "0.2 mg",
          route: "Intravenous",
          frequency: "Q3H PRN",
          prn_reason: "Breakthrough/Emergent pain",
        },
      },
    }),
    action({
      id: "p6.accept_order",
      phase: "order_entry",
      action: "accept_order",
      semanticTarget: EHR_TARGETS.acceptOrderButton,
      reason: "Move order into pending orders",
      preconditions: ["order_configured"],
      postconditions: ["order_pending_signature"],
      safetyLevel: "clinician_confirmed",
      replayAllowed: false,
    }),
    action({
      id: "p6.manual_sign_orders",
      phase: "order_entry",
      action: "manual_sign_only",
      semanticTarget: EHR_TARGETS.signOrdersButton,
      reason: "Clinician must be the final signer on medication orders",
      preconditions: ["order_pending_signature"],
      postconditions: ["order_signed_by_clinician"],
      safetyLevel: "prohibited",
      replayAllowed: false,
    }),
  ];
}

const TRANSITION_MAP: Record<string, EhrWorkflowState> = {
  "p1.confirm_patient_context": "PATIENT_CONTEXT_OPEN",
  "p2.click_chart_review": "CHART_REVIEW_OPEN",
  "p2.click_notes_subtab": "CHART_REVIEW_OPEN",
  "p2.open_filter": "NOTES_FILTER_OPEN",
  "p2.select_inpatient_type": "NOTES_FILTER_OPEN",
  "p2.open_inpatient_note": "INPATIENT_NOTE_SELECTED",
  "p3.select_note_text": "INPATIENT_NOTE_SELECTED",
  "p3.copy_note_text": "NOTE_TEXT_CAPTURED",
  "p4.click_notes_activity": "NOTES_ACTIVITY_OPEN",
  "p4.iterate_note_rows": "MULTI_NOTE_REVIEW",
  "p4.open_each_note_preview": "MULTI_NOTE_REVIEW",
  "p4.copy_each_note": "CONTEXT_BUNDLE_READY",
  "p5.click_new_note": "NEW_NOTE_EDITOR_OPEN",
  "p5.wait_for_editor": "NEW_NOTE_EDITOR_OPEN",
  "p5.paste_draft": "DRAFT_NOTE_INSERTED",
  "p5.clinician_review_required": "NOTE_REVIEW_REQUIRED",
  "p5.manual_sign_note": "NOTE_SIGNED_BY_CLINICIAN",
  "p6.click_orders_tab": "ORDERS_OPEN",
  "p6.click_order_search": "ORDER_SEARCH_ACTIVE",
  "p6.type_dilaudid": "ORDER_SEARCH_ACTIVE",
  "p6.select_hydromorphone": "MEDICATION_SELECTED",
  "p6.handle_advisory": "ADVISORY_OPEN",
  "p6.select_reason": "ADVISORY_OPEN",
  "p6.configure_order": "ORDER_COMPOSER_OPEN",
  "p6.accept_order": "ORDER_PENDING_SIGNATURE",
  "p6.manual_sign_orders": "ORDER_SIGNED_BY_CLINICIAN",
};

export function buildTransitions(actions: EhrAction[]): WorkflowTransition[] {
  let prev: EhrWorkflowState | null = null;
  const transitions: WorkflowTransition[] = [];
  for (const a of actions) {
    const to = TRANSITION_MAP[a.id];
    if (!to) continue;
    transitions.push({
      from: prev,
      to,
      trigger: a.id,
      evidence: a.semanticTarget.label,
      confidence: a.safetyLevel === "prohibited" ? 1.0 : 0.85,
      timestamp: new Date().toISOString(),
      safetyLevel: a.safetyLevel,
    });
    prev = to;
  }
  return transitions;
}
