import type { AnthropicLike } from "./drafter";
import type { ClinicalContextBundle, ClinicalSourceNote } from "./types";

const NOT_FOUND = "[Not found in provided notes]";

export interface NotesSummaryPerNote {
  source_id: string;
  note_type?: string;
  service?: string;
  timestamp?: string;
  one_liner: string;
}

export interface NotesSummary {
  scope: string;
  overall: string;
  bullets: string[];
  per_note: NotesSummaryPerNote[];
  uncovered: string[];
  warnings: string[];
  generator: "anthropic" | "fixture_grounded_fallback";
}

export interface NotesSummarizerOptions {
  scope?: string;
  anthropicClient?: AnthropicLike | null;
  anthropicModel?: string;
}

const SYSTEM_PROMPT = `You are a clinical summarization assistant.
You ONLY summarize content drawn from the source notes the user provides.
Never invent diagnoses, medications, doses, allergies, lab values, imaging results, procedures, orders, or demographics.
If a requested element is not in the source notes, write exactly: ${NOT_FOUND}
Every per-note one-liner must reference the provided source_id.
Output is a READ-ONLY summary for clinician review inside Specter — it is not a draft note for signing and is never written back into the EHR.
Return ONLY valid JSON matching the requested schema.`;

const REQUIRED_SHAPE = {
  scope: "string",
  overall: "string",
  bullets: ["string"],
  per_note: [
    {
      source_id: "string",
      note_type: "string?",
      service: "string?",
      timestamp: "string?",
      one_liner: "string",
    },
  ],
  uncovered: ["string"],
  warnings: ["string"],
};

function firstSentence(text: string): string {
  const trimmed = text.replace(/\s+/g, " ").trim();
  if (!trimmed) return "";
  const match = trimmed.match(/^(.{1,200}?[.?!])(\s|$)/);
  return (match ? match[1] : trimmed.slice(0, 200)).trim();
}

function deriveOneLiner(s: ClinicalSourceNote): string {
  const sec = s.extractedSections ?? {};
  const candidate =
    sec.assessmentPlan || sec.hpi || sec.chiefComplaint || s.rawText;
  const sentence = firstSentence(candidate);
  return sentence || NOT_FOUND;
}

function buildFallbackSummary(
  bundle: ClinicalContextBundle,
  scope: string,
): NotesSummary {
  const sources = bundle.sources;
  if (sources.length === 0) {
    return {
      scope,
      overall: NOT_FOUND,
      bullets: [],
      per_note: [],
      uncovered: ["all sections — no sources provided"],
      warnings: [
        "No source notes were captured. Refusing to summarize from empty context.",
        "Clinician must verify all content before any clinical use.",
      ],
      generator: "fixture_grounded_fallback",
    };
  }

  const perNote: NotesSummaryPerNote[] = sources.map((s) => ({
    source_id: s.id,
    note_type: s.noteType,
    service: s.service,
    timestamp: s.timestamp,
    one_liner: deriveOneLiner(s),
  }));

  const bullets: string[] = [];
  const seen = new Set<string>();
  for (const s of sources) {
    const sec = s.extractedSections ?? {};
    const items: Array<[string, string | undefined]> = [
      ["Chief complaint", sec.chiefComplaint],
      ["A&P", sec.assessmentPlan],
      ["Imaging", sec.imaging],
      ["Labs", sec.labs],
    ];
    for (const [label, value] of items) {
      if (!value) continue;
      const oneline = firstSentence(value);
      if (!oneline) continue;
      const key = `${label}:${oneline.toLowerCase()}`;
      if (seen.has(key)) continue;
      seen.add(key);
      bullets.push(`${label} (${s.id}): ${oneline}`);
    }
  }

  const overallParts = sources.map(
    (s) => `${s.id}${s.noteType ? ` (${s.noteType})` : ""}`,
  );
  const overall = `Synthesized read-only summary across ${sources.length} captured note(s) from APeX Chart Review > Notes: ${overallParts.join(", ")}.`;

  const uncovered: string[] = [];
  if (!sources.some((s) => s.extractedSections?.allergies)) {
    uncovered.push("Allergies not present in any captured note");
  }
  if (!sources.some((s) => s.extractedSections?.meds)) {
    uncovered.push("Medications not present in any captured note");
  }

  return {
    scope,
    overall,
    bullets,
    per_note: perNote,
    uncovered,
    warnings: [
      "Clinician must verify all content before any clinical use.",
      "Generated by source-grounded fallback (no LLM call).",
    ],
    generator: "fixture_grounded_fallback",
  };
}

function extractJsonBlock(text: string): unknown {
  const fenced = text.match(/```(?:json)?\s*([\s\S]*?)```/i);
  const candidate = fenced?.[1] || text.match(/\{[\s\S]*\}/)?.[0] || text;
  return JSON.parse(candidate);
}

function coerceStringArray(value: unknown): string[] {
  return Array.isArray(value)
    ? value.filter((v): v is string => typeof v === "string")
    : [];
}

function optionalString(value: unknown): string | undefined {
  return typeof value === "string" && value.trim().length > 0
    ? value
    : undefined;
}

function coercePerNote(value: unknown): NotesSummaryPerNote[] {
  if (!Array.isArray(value)) return [];
  return value
    .filter((v): v is Record<string, unknown> =>
      Boolean(v && typeof v === "object"),
    )
    .map((entry) => ({
      source_id: typeof entry.source_id === "string" ? entry.source_id : "",
      note_type: optionalString(entry.note_type),
      service: optionalString(entry.service),
      timestamp: optionalString(entry.timestamp),
      one_liner:
        typeof entry.one_liner === "string" && entry.one_liner.trim()
          ? entry.one_liner
          : NOT_FOUND,
    }))
    .filter((e) => e.source_id);
}

function normalizeAnthropicSummary(raw: unknown, scope: string): NotesSummary {
  const obj = (raw && typeof raw === "object" ? raw : {}) as Record<
    string,
    unknown
  >;
  return {
    scope:
      typeof obj.scope === "string" && obj.scope.trim() ? obj.scope : scope,
    overall: typeof obj.overall === "string" ? obj.overall : NOT_FOUND,
    bullets: coerceStringArray(obj.bullets),
    per_note: coercePerNote(obj.per_note),
    uncovered: coerceStringArray(obj.uncovered),
    warnings: [
      ...coerceStringArray(obj.warnings),
      "Clinician must verify all content before any clinical use.",
    ],
    generator: "anthropic",
  };
}

export async function generateNotesSummary(
  bundle: ClinicalContextBundle,
  options: NotesSummarizerOptions = {},
): Promise<NotesSummary> {
  const scope = options.scope || "APeX Chart Review > Notes";

  if (bundle.sources.length === 0) {
    return buildFallbackSummary(bundle, scope);
  }

  const client = options.anthropicClient ?? null;
  if (!client) {
    return buildFallbackSummary(bundle, scope);
  }

  try {
    const userPayload = {
      scope,
      sources: bundle.sources.map((s) => ({
        source_id: s.id,
        note_type: s.noteType,
        service: s.service,
        author: s.author,
        timestamp: s.timestamp,
        raw_text: s.rawText,
      })),
      required_shape: REQUIRED_SHAPE,
      rules: [
        "Use ONLY content present in sources.",
        "If an element is missing, output exactly: " + NOT_FOUND,
        "Every per_note entry must use a source_id from the input.",
        "Do not invent diagnoses, meds, allergies, labs, imaging, procedures, orders, or demographics.",
        "This is a read-only summary; never recommend signing or order entry.",
      ],
    };
    const response = await client.messages.create({
      model: options.anthropicModel || "claude-opus-4-7",
      max_tokens: 2048,
      system: SYSTEM_PROMPT,
      messages: [
        { role: "user", content: JSON.stringify(userPayload, null, 2) },
      ],
    });
    const text = response.content
      .map((p) =>
        p.type === "text" && typeof p.text === "string" ? p.text : "",
      )
      .join("\n");
    const parsed = extractJsonBlock(text);
    return normalizeAnthropicSummary(parsed, scope);
  } catch {
    return buildFallbackSummary(bundle, scope);
  }
}

export interface SummaryValidationResult {
  ok: boolean;
  errors: string[];
}

export function validateNotesSummary(
  summary: NotesSummary,
  bundle: ClinicalContextBundle,
): SummaryValidationResult {
  const errors: string[] = [];
  const validIds = new Set(bundle.sources.map((s) => s.id));

  for (const entry of summary.per_note) {
    if (!validIds.has(entry.source_id)) {
      errors.push(`per_note references unknown source_id ${entry.source_id}`);
    }
  }

  if (
    bundle.sources.length > 0 &&
    summary.per_note.length === 0 &&
    summary.overall !== NOT_FOUND
  ) {
    errors.push("summary has populated overall but no per_note entries");
  }

  if (
    !summary.warnings.some((w) => /clinician.*verify|verify.*clinical/i.test(w))
  ) {
    errors.push("missing clinician-verification warning");
  }

  return { ok: errors.length === 0, errors };
}
